curl https://ark.cn-beijing.volces.com/api/v3/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ARK_API_KEY" \
  -d '{
     "model": "doubao-seed-1-6-lite-251015",
     "max_completion_tokens": 65535,
     "messages": [
        {
            "content": [
                
                {
                    "text": "早上好，今天天气怎么样？",
                    "type": "text"
                }
            ],
            "role": "user"
        }
    ],
     "reasoning_effort": "medium"
}'